### ISSUE TITLE
Preview the Template

### ISSUE THREAD

**Issue by abnet3** [asoftwareworld/ASW-Form-Builder#10]
I am facing this error when i import it in an another module for pages

BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by abnet3** [comment]
how can i save or preview the template?? <asw-preview-template [formContainer]="jsonData"></asw-preview-template>
is not working?

**Comment by asoftwareworld** [comment]
Thanks for your input on this. 
Our technical team is working on this will update you soon.
