### ISSUE TITLE
Bug when drag in same row

### ISSUE THREAD

**Issue by DavidRomaniuk** [asoftwareworld/ASW-Form-Builder#37]
![imagen](https://user-images.githubusercontent.com/74748580/185646159-7554e673-1dec-43a5-9147-c01e6e18478e.png)

Hello! When you drag a control between mid-row size controls, the view starts to break. I found an example of dragging in a grid that may help you. Very good product!

https://stackblitz.com/edit/angular-dragdrop-grid?file=src%2Fapp%2Fapp.component.ts

**Comment by asoftwareworld** [comment]
Thank you for input and feedback. 

Will surly updates on this.

**Comment by asoftwareworld** [comment]
This issue is resolved in ASW form builder pro version. Please have a look into it. Below is the demo url for the same
http://localhost:4200/#/product/form-builder/demo
