### ISSUE TITLE
Feat(COMPONENT): Image Control Changes

### ISSUE THREAD

**Issue by KhushbuAjmeraEXt** [asoftwareworld/ASW-Form-Builder#40]
**Feature Description**
1. Make the “Select Image shape” to be square by default for the Image control.
2. We just need browse button for uploading the image, so wanted to remove the default “ASW Image” placeholder.
3. We need image size to be configurable, so that user can set width and height of the image in the setting itself. 
4. Please add signature icon in preview as well.

**Comment by asoftwareworld** [comment]
@KhushbuAjmeraEXt 
We appreciate your recommendation/response, your suggestions are precious to us.
As per your request, we have implemented all the changes and released a new version [5.0.4](https://github.com/asoftwareworld/ASW-Form-Builder/releases/tag/v5.0.4).
