### ISSUE TITLE
Calculated Input Issue

### ISSUE THREAD

**Issue by KhushbuAjmeraEXt** [asoftwareworld/ASW-Form-Builder#42]
**Describe the bug**
Calculated input always takes numeric input 1 in their formula, we are not able to change the formula.

**To Reproduce**
1. Set three number inputs num1, num2, num3 and add one calculated input. 
2. Set formula num2 * num3 (Multiplication) in the calculated input

**Expected behavior**
Should set the formula num2 * num3

**Actual behavior**
Formula automatically changes to num1 * num2

**Comment by asoftwareworld** [comment]
Issue fixed in version 5.0.5
