### ISSUE TITLE
Image control Bug 

### ISSUE THREAD

**Issue by reena2013** [asoftwareworld/ASW-Form-Builder#44]
1. No max height and max width for image control.
2. Because of the tooltip for upload button of an image control and signature control, we are not able to select edit for the control.
3. Removal of default image for ASW in image control.
4. For the image control, alignment properties i.e. center and left are working as left aligned.

**Comment by asoftwareworld** [comment]
We have tried the same but somehow it is not reproducible for us. Could you please provide the steps?

**Comment by reena2013** [comment]
> 1. No max height and max width for image control.
> 2. Because of the tooltip for upload button of an image control and signature control, we are not able to select edit for the control.
> 3. Removal of default image for ASW in image control.
> 4. For the image control, alignment properties i.e. center and left are working as left aligned.

**Comment by reena2013** [comment]
As discussed, 3 issues are there.
1.No max height and max width for image control.
2.Removal of default image for ASW in image control.
3.For the image control, alignment properties i.e. center and left are working as left aligned.
