### ISSUE TITLE
Feat(COMPONENT): title

### ISSUE THREAD

**Issue by adityawiryaa** [asoftwareworld/ASW-Form-Builder#46]
**Feature Description**
- Add controls time ( because already have date)
- Add controls DateTime
- Add controls to can show data from API and select like checkbox
**Use Case**
Describe the use case(s) that the proposed feature would enable.
- add controls to can show my API into Form

**Comment by asoftwareworld** [comment]
The functionality to bind data from an API to select and checkbox controls has already been added in the PRO version. To access this feature, you need to subscribe to the PRO version. Additionally, we will include the Time control in the next release.

below is the PRO Demo Link
https://asoftwareworld.com/#/product/form-builder/demo

**Comment by adityawiryaa** [comment]
okay noted, thank you.

**Comment by asoftwareworld** [comment]
A time control has been added to the Pro version. Please take a look at it
below is the PRO Demo Link
[Demo](https://asoftwareworld.com/product/form-builder/demo)
